Update roborazzi to v1.58.0 (#1732)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
|
[io.github.takahirom.roborazzi](https://redirect.github.com/takahirom/roborazzi)
| plugin | minor | `1.57.0` -> `1.58.0` |
|
[io.github.takahirom.roborazzi:roborazzi-core](https://redirect.github.com/takahirom/roborazzi)
| dependencies | minor | `1.57.0` -> `1.58.0` |
|
[io.github.takahirom.roborazzi:roborazzi-compose-desktop](https://redirect.github.com/takahirom/roborazzi)
| dependencies | minor | `1.57.0` -> `1.58.0` |

---

### Release Notes

<details>
<summary>takahirom/roborazzi (io.github.takahirom.roborazzi)</summary>

###
[`v1.58.0`](https://redirect.github.com/takahirom/roborazzi/releases/tag/1.58.0)

[Compare
Source](https://redirect.github.com/takahirom/roborazzi/compare/1.57.0...1.58.0)

##### Bugfix: Fixed NoClassDefFoundError in RoborazziPlugin when the
Android Plugin is not applied

Previously, we never touched the Android Plugin class when it wasn’t in
use; nevertheless, a NoClassDefFoundError was raised because the plugin
contained a method that referenced the Android Plugin class. I therefore
extracted Android-related code into a separate class to resolve the
issue. Thank you, [@&#8203;rnett](https://redirect.github.com/rnett),
for reporting this.

##### Update: Device qualifiers

You can now specify device qualifiers via RobolectricDeviceQualifiers.
The list has been expanded with new devices such as Pixel9, XRGlasses,
and even AIGlasses!
Thank you, [@&#8203;joergmis](https://redirect.github.com/joergmis), for
your contribution.

##### What's Changed

- Ensure StoreScreenshot records Android host tests by
[@&#8203;takahirom](https://redirect.github.com/takahirom) in
[https://github.com/takahirom/roborazzi/pull/790](https://redirect.github.com/takahirom/roborazzi/pull/790)
- Use debug unit test for roborazzi-core by
[@&#8203;takahirom](https://redirect.github.com/takahirom) in
[https://github.com/takahirom/roborazzi/pull/792](https://redirect.github.com/takahirom/roborazzi/pull/792)
- Update device qualifiers by
[@&#8203;joergmis](https://redirect.github.com/joergmis) in
[https://github.com/takahirom/roborazzi/pull/793](https://redirect.github.com/takahirom/roborazzi/pull/793)
- Isolate Android-specific code to support non-Android KMP projects by
[@&#8203;takahirom](https://redirect.github.com/takahirom) in
[https://github.com/takahirom/roborazzi/pull/795](https://redirect.github.com/takahirom/roborazzi/pull/795)

##### New Contributors

- [@&#8203;joergmis](https://redirect.github.com/joergmis) made their
first contribution in
[https://github.com/takahirom/roborazzi/pull/793](https://redirect.github.com/takahirom/roborazzi/pull/793)

**Full Changelog**:
https://github.com/takahirom/roborazzi/compare/1.57.0...1.58.0

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Renovate
Bot](https://redirect.github.com/renovatebot/renovate).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4yNjQuMCIsInVwZGF0ZWRJblZlciI6IjM5LjI2NC4wIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->