Update kotlin monorepo to v2.3.10 (#1734)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [org.jetbrains.kotlin.plugin.serialization](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | plugin |
patch | `2.3.0` -> `2.3.10` |
|
[org.jetbrains.kotlin.plugin.sam.with.receiver](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | plugin |
patch | `2.3.0` -> `2.3.10` |
| [org.jetbrains.kotlin.plugin.compose](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | plugin |
patch | `2.3.0` -> `2.3.10` |
| [org.jetbrains.kotlin.multiplatform](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | plugin |
patch | `2.3.0` -> `2.3.10` |
| [org.jetbrains.kotlin.jvm](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | plugin |
patch | `2.3.0` -> `2.3.10` |
| [org.jetbrains.kotlin:kotlin-test](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | dependencies
| patch | `2.3.0` -> `2.3.10` |
| [org.jetbrains.kotlin:kotlin-reflect](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | dependencies
| patch | `2.3.0` -> `2.3.10` |
|
[org.jetbrains.kotlin:kotlin-gradle-plugins-bom](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | dependencies
| patch | `2.3.0` -> `2.3.10` |
| [org.jetbrains.kotlin:kotlin-bom](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | dependencies
| patch | `2.3.0` -> `2.3.10` |
| [org.jetbrains.kotlin:kotlin-gradle-plugin](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | dependencies
| patch | `2.3.0` -> `2.3.10` |
|
[org.jetbrains.kotlin:compose-compiler-gradle-plugin](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | dependencies
| patch | `2.3.0` -> `2.3.10` |

---

### Release Notes

<details>
<summary>JetBrains/kotlin
(org.jetbrains.kotlin.plugin.serialization)</summary>

###
[`v2.3.10`](https://redirect.github.com/JetBrains/kotlin/blob/HEAD/ChangeLog.md#2310)

##### Compiler

- [`KT-83984`](https://youtrack.jetbrains.com/issue/KT-83984) Data races
around kotlinx.serialization plugin protobuf extensions registration
- [`KT-83317`](https://youtrack.jetbrains.com/issue/KT-83317)
ClassCastException: with cast kotlin.UInt to java.lang.Number when
defining constant
- [`KT-83031`](https://youtrack.jetbrains.com/issue/KT-83031) K2:
unstable resolution of EnhancedNullability from type-use NotNull in
presence of unused code
- [`KT-81700`](https://youtrack.jetbrains.com/issue/KT-81700) flaky
overload resolution behaviors (false-positive errors, different final
candidates, compile-time failures)
- [`KT-83983`](https://youtrack.jetbrains.com/issue/KT-83983) Revert of
KT-83081
- [`KT-83314`](https://youtrack.jetbrains.com/issue/KT-83314) JSpecify
`@NullMarked` changes Java equals(Object) to equals(Any?) causing
override conflict in Kotlin 2.3
- [`KT-82863`](https://youtrack.jetbrains.com/issue/KT-82863) `@NoInfer`
regression since 2.2.20
- [`KT-82841`](https://youtrack.jetbrains.com/issue/KT-82841)
"kotlin.NoWhenBranchMatchedException" in `when` with `!is` check &
non-sealed class in the middle of hierarchy

##### JVM. Reflection

- [`KT-83608`](https://youtrack.jetbrains.com/issue/KT-83608)
Kotlin-reflect: "Unknown origin of public abstract operator fun
invoke(p1: P1, p2: P2): R"
- [`KT-83361`](https://youtrack.jetbrains.com/issue/KT-83361)
"KotlinReflectionInternalError: Type parameter not found: 0" on super
types with Kotlin 2.3.0
- [`KT-42199`](https://youtrack.jetbrains.com/issue/KT-42199)
"KotlinReflectionInternalError: Unknown origin of public abstract
operator fun invoke" on function reference to FunctionN.invoke
- [`KT-81024`](https://youtrack.jetbrains.com/issue/KT-81024)
Reflection: New KType implementation fails on arguments comparison for a
Nothing type parameter

##### Tools. Compiler Plugins

- [`KT-83266`](https://youtrack.jetbrains.com/issue/KT-83266)
"Unsupported class file major version 69" for
"produceReleaseComposeMapping" task with Kotlin 2.3
- [`KT-83099`](https://youtrack.jetbrains.com/issue/KT-83099) Compose
compiler does not generate stack trace mappings for project files

##### Tools. Gradle

- [`KT-83070`](https://youtrack.jetbrains.com/issue/KT-83070) The KGP
api reference is missing a description
- [`KT-82459`](https://youtrack.jetbrains.com/issue/KT-82459) Improve
iOS simulator boot implementation

##### Tools. Gradle. JS

- [`KT-82946`](https://youtrack.jetbrains.com/issue/KT-82946) Js, Wasm:
Upgrade NPM dependencies

##### Tools. Gradle. Multiplatform

- [`KT-83687`](https://youtrack.jetbrains.com/issue/KT-83687) Revert
deprecation of 'androidTarget' for AGP lower than 9

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Renovate
Bot](https://redirect.github.com/renovatebot/renovate).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4yNjQuMCIsInVwZGF0ZWRJblZlciI6IjM5LjI2NC4wIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->