Update okio to v3.15.0 (#1443)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
|
[com.squareup.okio:okio-fakefilesystem](https://redirect.github.com/square/okio)
| dependencies | minor | `3.13.0` -> `3.15.0` |
| [com.squareup.okio:okio](https://redirect.github.com/square/okio) |
dependencies | minor | `3.13.0` -> `3.15.0` |

---

### Release Notes

<details>
<summary>square/okio (com.squareup.okio:okio-fakefilesystem)</summary>

###
[`v3.15.0`](https://redirect.github.com/square/okio/blob/HEAD/CHANGELOG.md#Version-3150)

*2025-07-01*

- Upgrade: \[kotlinx-datetime
0.7.0-0.6.x-compat]\[datetime\_0\_7\_0\_compat]. The previous 3.14.0
release, `FakeFileSystem` broke binary-compatibility for calls to
`FakeFileSystem()`. This
    restores that compatibility.

- Breaking: Change `FakeFileSystem.clock` from a JVM field to a
property. This avoids a crash
running Okio in a Gradle 8.x plugin. This change is not
binary-compatible.

###
[`v3.14.0`](https://redirect.github.com/square/okio/blob/HEAD/CHANGELOG.md#Version-3140)

*2025-06-28*

- Upgrade: \[kotlinx-datetime 0.7.0]\[datetime\_0\_7\_0]. This impacts
the `okio-fakefilesystem`
artifact only. This is a binary-incompatible backwards-incompatible
change that cannot co-exist
with previous releases of `okio-fakefilesystem`! If you observe a
`NoSuchMethodError` calling
`FakeFileSystem.init`, update the calling code to this release (or
newer) and recompile. We don't
like imposing backwards-incompatible changes like this on you and do so
regretfully.

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Renovate
Bot](https://redirect.github.com/renovatebot/renovate).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4yNjQuMCIsInVwZGF0ZWRJblZlciI6IjM5LjI2NC4wIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->