Update kotlin monorepo to v1.9.10 (#543)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [org.jetbrains.kotlin.jvm](https://kotlinlang.org/)
([source](https://togithub.com/JetBrains/kotlin)) | plugin | patch |
`1.9.0` -> `1.9.10` |
| [org.jetbrains.kotlin:kotlin-reflect](https://kotlinlang.org/)
([source](https://togithub.com/JetBrains/kotlin)) | dependencies | patch
| `1.9.0` -> `1.9.10` |
| [org.jetbrains.kotlin:kotlin-bom](https://kotlinlang.org/)
([source](https://togithub.com/JetBrains/kotlin)) | dependencies | patch
| `1.9.0` -> `1.9.10` |
| [org.jetbrains.kotlin:kotlin-gradle-plugin](https://kotlinlang.org/)
([source](https://togithub.com/JetBrains/kotlin)) | dependencies | patch
| `1.9.0` -> `1.9.10` |

---

### ⚠ Dependency Lookup Warnings ⚠

Warnings were logged while processing this repo. Please check the
Dependency Dashboard for more information.

---

### Release Notes

<details>
<summary>JetBrains/kotlin (org.jetbrains.kotlin.jvm)</summary>

###
[`v1.9.10`](https://togithub.com/JetBrains/kotlin/releases/tag/v1.9.10):
Kotlin 1.9.10

##### Changelog

##### Compiler

- [`KT-60769`](https://youtrack.jetbrains.com/issue/KT-60769) Partially
revert KT-58371
- [`KT-60659`](https://youtrack.jetbrains.com/issue/KT-60659) Incorrect
'unresolved reference: addFirst' error with JDK 21
- [`KT-60371`](https://youtrack.jetbrains.com/issue/KT-60371) Native
custom allocator link error
- [`KT-60986`](https://youtrack.jetbrains.com/issue/KT-60986) Native:
static caches with custom runtime options are broken on Linux
- [`KT-60770`](https://youtrack.jetbrains.com/issue/KT-60770) Fix
false-positive ABSTRACT_MEMBER_NOT_IMPLEMENTED on toArray with JDK 21
- [`KT-60231`](https://youtrack.jetbrains.com/issue/KT-60231)
NoClassDefFoundError: $$$$$NON_LOCAL_RETURN$$$$$ after upgrade to Kotlin
1.9.0

##### JavaScript

- [`KT-60785`](https://youtrack.jetbrains.com/issue/KT-60785) KJS:
Destructured value class in suspend function fails with Uncaught
TypeError: can't convert to primitive type error
- [`KT-60852`](https://youtrack.jetbrains.com/issue/KT-60852) Kotlin
JS(IR): IllegalArgumentException: Cross module dependency resolution
failed when updating to Kotlin 1.9.0
- [`KT-57509`](https://youtrack.jetbrains.com/issue/KT-57509) KJS:
Compiler generates native JS operator == for comparing values with Any
type

##### Native

- [`KT-60230`](https://youtrack.jetbrains.com/issue/KT-60230) Native:
"unknown options: -ios_simulator_version_min -sdk_version" with Xcode 15
beta 3
- [`KT-60758`](https://youtrack.jetbrains.com/issue/KT-60758) Native:
Building for 'iOS-simulator', but linking in dylib built for 'iOS' in
Xcode 15 beta 4

##### Native. C and ObjC Import

- [`KT-59167`](https://youtrack.jetbrains.com/issue/KT-59167) Native:
cinterop is unable to build interop libraries against the Xcode 15 Beta
1

##### Tools. Gradle

- [`KT-61147`](https://youtrack.jetbrains.com/issue/KT-61147) Kotlin
Compiler 1.9.0 bundles a stripped unshadowed version of Gson
- [`KT-60543`](https://youtrack.jetbrains.com/issue/KT-60543)
NoClassDefFoundError for com/gradle/scan/plugin/BuildScanExtension

##### Checksums

| File | Sha256 |
| --- | --- |
| kotlin-compiler-1.9.10.zip |
7d74863deecf8e0f28ea54c3735feab003d0eac67e8d3a791254b16889c20342 |
| kotlin-native-linux-x86\_64-1.9.10.tar.gz |
1db3679919f4449514e9d82451e7dfa73558ac9bc80b82579cd74d452c8faa5b |
| kotlin-native-macos-x86\_64-1.9.10.tar.gz |
f5650f2560438a692803d8fe07124529c19f1972f84fe09cfa2329b93f43828d |
| kotlin-native-macos-aarch64-1.9.10.tar.gz |
d2cf5a484ac0808ab29fd3f6099df7c07330f81f3cbab949947e42e36138c3de |
| kotlin-native-windows-x86\_64-1.9.10.zip |
a34d56661455e94e1ba4dd09ec3c1adac6148fdedcf55eefb9a79c8ed01ff02c |

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Renovate
Bot](https://togithub.com/renovatebot/renovate).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNi41Ny40IiwidXBkYXRlZEluVmVyIjoiMzYuNTcuNCIsInRhcmdldEJyYW5jaCI6Im1haW4ifQ==-->

---------

Co-authored-by: Zac Sweers <pandanomic@gmail.com>