Update kotlin monorepo to v2.2.10 (#1499)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [org.jetbrains.kotlin.plugin.serialization](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | plugin |
patch | `2.2.0` -> `2.2.10` |
|
[org.jetbrains.kotlin.plugin.sam.with.receiver](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | plugin |
patch | `2.2.0` -> `2.2.10` |
| [org.jetbrains.kotlin.plugin.compose](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | plugin |
patch | `2.2.0` -> `2.2.10` |
| [org.jetbrains.kotlin.multiplatform](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | plugin |
patch | `2.2.0` -> `2.2.10` |
| [org.jetbrains.kotlin.jvm](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | plugin |
patch | `2.2.0` -> `2.2.10` |
| [org.jetbrains.kotlin:kotlin-test](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | dependencies
| patch | `2.2.0` -> `2.2.10` |
| [org.jetbrains.kotlin:kotlin-reflect](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | dependencies
| patch | `2.2.0` -> `2.2.10` |
|
[org.jetbrains.kotlin:kotlin-gradle-plugins-bom](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | dependencies
| patch | `2.2.0` -> `2.2.10` |
| [org.jetbrains.kotlin:kotlin-bom](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | dependencies
| patch | `2.2.0` -> `2.2.10` |
| [org.jetbrains.kotlin:kotlin-gradle-plugin](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | dependencies
| patch | `2.2.0` -> `2.2.10` |
|
[org.jetbrains.kotlin:compose-compiler-gradle-plugin](https://kotlinlang.org/)
([source](https://redirect.github.com/JetBrains/kotlin)) | dependencies
| patch | `2.2.0` -> `2.2.10` |

---

### Release Notes

<details>
<summary>JetBrains/kotlin
(org.jetbrains.kotlin.plugin.serialization)</summary>

###
[`v2.2.10`](https://redirect.github.com/JetBrains/kotlin/blob/HEAD/ChangeLog.md#2210)

##### Compiler

- [`KT-79276`](https://youtrack.jetbrains.com/issue/KT-79276) Dexing
fails with "Cannot read field X because <local0> is null" with 2.2.0
- [`KT-79442`](https://youtrack.jetbrains.com/issue/KT-79442) "Multiple
annotations of type kotlin.coroutines.jvm.internal.DebugMetadata":
2.2.0-Beta1 generates broken code with JVM default suspend methods in
interfaces
- [`KT-78815`](https://youtrack.jetbrains.com/issue/KT-78815) `Symbol
not found: __ZNSt3__117bad_function_callD1Ev` error on iOS 15.5
simulator in Xcode 16.3 after update to 2.2.0-Beta2
- [`KT-78501`](https://youtrack.jetbrains.com/issue/KT-78501) K2:
Missing \[ABSTRACT_SUPER_CALL] diagnostics for delegated interface
method leads to AssertionError: isCompiledToJvmDefault during IR
lowering
- [`KT-78479`](https://youtrack.jetbrains.com/issue/KT-78479) IR
lowering failed / Unexpected null argument for composable call
- [`KT-76477`](https://youtrack.jetbrains.com/issue/KT-76477)
Kotlin/Native: fix compiler performance reporting in sources->klib and
klibs->binary
- [`KT-78736`](https://youtrack.jetbrains.com/issue/KT-78736) Missing
\[NOT_YET_SUPPORTED_IN_INLINE] diagnostics because of incorrect context
update
- [`KT-77685`](https://youtrack.jetbrains.com/issue/KT-77685)
"IllegalArgumentException: Sequence contains more than one matching
element"
- [`KT-76365`](https://youtrack.jetbrains.com/issue/KT-76365) K2:
Missing ABSTRACT_SUPER_CALL
- [`KT-78352`](https://youtrack.jetbrains.com/issue/KT-78352)
False-positive IDENTITY_SENSITIVE_OPERATIONS_WITH_VALUE_TYPE when
comparing with equality operator (==)

##### Compose compiler

- [`KT-78479`](https://youtrack.jetbrains.com/issue/KT-78479) Ensure
that default transform affects functions entered through a call
- [`KT-78490`](https://youtrack.jetbrains.com/issue/KT-78490) Fix
visibility for default wrappers of protected methods
- [`b/408492167`](https://issuetracker.google.com/issues/408492167) Emit
parameter names in Compose source information

##### JavaScript

- [`KT-79050`](https://youtrack.jetbrains.com/issue/KT-79050) KJS / IC:
"Unexpected body of primary constructor for processing irClass"
- [`KT-79089`](https://youtrack.jetbrains.com/issue/KT-79089) KJS: Could
not load reporter / Cannot find module 'mocha' when running jsNode tests

##### Native

- [`KT-79075`](https://youtrack.jetbrains.com/issue/KT-79075) Stuck on
Kotlin_getSourceInfo_core_symbolication
- [`KT-76178`](https://youtrack.jetbrains.com/issue/KT-76178) LLVM
Update: symbol '\__ZnwmSt19\__type_descriptor_t' missing

##### Native. Runtime. Memory

- [`KT-78925`](https://youtrack.jetbrains.com/issue/KT-78925) Crash
SIGABRT on Apple Watch after updating Kotlin to 2.2.0

##### Tools. CLI

- [`KT-77445`](https://youtrack.jetbrains.com/issue/KT-77445)
UNRESOLVED_REFERENCE when importing classes from kotlin-stdlib
- [`KT-78263`](https://youtrack.jetbrains.com/issue/KT-78263)
java.lang.NoClassDefFoundError: Could not initialize class
com.intellij.psi.impl.PsiSubstitutorImpl
- [`KT-78318`](https://youtrack.jetbrains.com/issue/KT-78318) Unresolved
reference when compiling kotlin/JS project on fresh master

##### Tools. Compiler Plugins

- [`KT-78490`](https://youtrack.jetbrains.com/issue/KT-78490)
"AssertionError: SyntheticAccessorLowering should not attempt to modify
other files" when calling protected open composable with default
argument
- [`KT-78038`](https://youtrack.jetbrains.com/issue/KT-78038) Make
jvm-abi-gen compiler plugin output classloader-friendly

##### Tools. Gradle

- [`KT-77023`](https://youtrack.jetbrains.com/issue/KT-77023) Support
creating KotlinJvmAndroidCompilation in KotlinBaseApiPlugin

##### Tools. Gradle. JS

- [`KT-78504`](https://youtrack.jetbrains.com/issue/KT-78504)
\[2.2.0-RC3] NPM Tasks in 2.2 RCs produce broken/unusable build cache
entries

##### Tools. Gradle. Multiplatform

- [`KT-77466`](https://youtrack.jetbrains.com/issue/KT-77466) KMP -
testFixturesApi and similar configurations do not affect jvmTestFixtures
source set
- [`KT-68646`](https://youtrack.jetbrains.com/issue/KT-68646) Compose
extension's metrics/reports dir should use subdirs based on target

##### Tools. Gradle. Native

- [`KT-77977`](https://youtrack.jetbrains.com/issue/KT-77977) "Unknown
hardware platform: riscv64" on JVM project build

##### Tools. Incremental Compile

- [`KT-78807`](https://youtrack.jetbrains.com/issue/KT-78807) Changing
ABI fingerprint on non-ABI changes when lambda passed to inlined
function

##### Tools. Kapt

- [`KT-77853`](https://youtrack.jetbrains.com/issue/KT-77853) K2 KAPT:
backend internal error: exception during IR fake override builder
- [`KT-79138`](https://youtrack.jetbrains.com/issue/KT-79138) K2: KAPT
Java Stub Gen: `Unresolved reference` with `@kotlin`.Metadata in Java in
2.2.0

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Renovate
Bot](https://redirect.github.com/renovatebot/renovate).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4yNjQuMCIsInVwZGF0ZWRJblZlciI6IjM5LjI2NC4wIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->