Update dependency org.jetbrains.kotlin.jvm to v1.7.21 (#156)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [org.jetbrains.kotlin.jvm](https://kotlinlang.org/)
([source](https://togithub.com/JetBrains/kotlin)) | plugin | patch |
`1.7.20` -> `1.7.21` |

---

### Release Notes

<details>
<summary>JetBrains/kotlin</summary>

###
[`v1.7.21`](https://togithub.com/JetBrains/kotlin/blob/HEAD/ChangeLog.md#&#8203;1721)

##### Compiler

- [`KT-54463`](https://youtrack.jetbrains.com/issue/KT-54463) Delegating
to a field with a platform type causes java.lang.NoSuchFieldError:
value$delegate
- [`KT-54509`](https://youtrack.jetbrains.com/issue/KT-54509) Ir
Interpreter: unable to evaluate string concatenation with "this" as
argument
- [`KT-54004`](https://youtrack.jetbrains.com/issue/KT-54004) Builder
type inference does not work correctly with variable assignment and
breaks run-time
- [`KT-54393`](https://youtrack.jetbrains.com/issue/KT-54393) Change in
behavior from 1.7.10 to 1.7.20 for java field override.
- [`KT-54615`](https://youtrack.jetbrains.com/issue/KT-54615) JVM:
Internal error in file lowering: java.lang.AssertionError: Error
occurred while optimizing an expression
- [`KT-54581`](https://youtrack.jetbrains.com/issue/KT-54581) JVM:
"VerifyError: Bad type on operand stack" with generic inline function
and `when` inside try-catch block
- [`KT-53146`](https://youtrack.jetbrains.com/issue/KT-53146) JVM IR:
unnecessary checkcast of null leads to NoClassDefFoundError if the type
isn't available at runtime
- [`KT-54600`](https://youtrack.jetbrains.com/issue/KT-54600) NPE on
passing nullable Kotlin lambda as Java's generic SAM interface with
`super` type bound
- [`KT-54707`](https://youtrack.jetbrains.com/issue/KT-54707)
"VerifyError: Bad type on operand stack" in inline call chain on a
nullable array value
- [`KT-54650`](https://youtrack.jetbrains.com/issue/KT-54650) Binary
incompatible ABI change in Kotlin 1.7.20
- [`KT-54802`](https://youtrack.jetbrains.com/issue/KT-54802)
"VerifyError: Bad type on operand stack" for inline functions on arrays

##### Native. Runtime. Memory

- [`KT-54498`](https://youtrack.jetbrains.com/issue/KT-54498)
Deprecation message of 'FreezingIsDeprecated' is not really helpful

##### Tools. Gradle. Multiplatform

- [`KT-54387`](https://youtrack.jetbrains.com/issue/KT-54387) Remove MPP
alpha stability warning
- [`KT-48436`](https://youtrack.jetbrains.com/issue/KT-48436) False
positive "The Kotlin source set androidAndroidTestRelease was configured
but not added to any Kotlin compilation"

##### Tools. JPS

- [`KT-45474`](https://youtrack.jetbrains.com/issue/KT-45474) False
positive NO_ELSE_IN_WHEN on sealed class with incremental compilation

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, click
this checkbox.

---

This PR has been generated by [Renovate
Bot](https://togithub.com/renovatebot/renovate).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzMi4xOTAuNiIsInVwZGF0ZWRJblZlciI6IjMyLjE5MC42In0=-->

Co-authored-by: Zac Sweers <pandanomic@gmail.com>